### ISSUE TITLE
Escaping looks buggy

### ISSUE THREAD

**Issue by martin-t** [kondziu/FML#2]
`print("\~\n", 5);` prints `5\n` (without a newline).
`print("\~\~\n", 5, 5);` prints `5\5` (with a newline).

The spec says "\~ converts to the character ~" - is that supposed to mean it prints a `~` or that it behaves the same as `~`? If it behaves the same (it *almost* does now), there's no way to print a literal `~`.

There's also no way to print a `\` according to the spec.

**Comment by kondziu** [comment]
Escaped `~` was meant to just produce the tilda. That's probably a dumb bug.

Spec should include `\\ -> \`.  That's an oversight.

**Comment by kondziu** [comment]
Fixed by a26948e2ceb902755f719a41cacb3a1e614c85ad
