### ISSUE TITLE
Scope of Variables inside Objects

### ISSUE THREAD

**Issue by slavim17** [kondziu/FML#4]
````
begin
    let x = 20;
    object begin
        let Z = x;
        let Y = object begin 
                        let a = 4;
                        let b = Z;
                    end;
    end;
end;
````

prints:

> thread 'main' panicked at 'Get global error: no such global: Z', src/bytecode/interpreter.rs:618:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

object(a, b) cannot see variable Z in object(Z, Y), but Z can see variable x, Is that desired?

**Comment by kondziu** [comment]
Yup. `Z` is a field, not a variable. There's no syntax for accessing it.

**Comment by slavim17** [comment]
If I managed to do the scoping to access from inner object to outer object fields is that wrong?

**Comment by kondziu** [comment]
I mean, it would be incorrect WRT language semantics and we might have a discussion about it, but I'm not going to censure you. I'm also reasonably certain you won't like the impact of this decision on your BC implementation.
