### ISSUE TITLE
Unclear spec on globals

### ISSUE THREAD

**Issue by Zagrosss** [kondziu/FML#5]
The spec states that globals refer to String program objects, see https://courses.fit.cvut.cz/NI-RUN/specs/bc.html#globals.
However, the reference compiler implementation seems to make it so that globals refer to Slot objects instead.

What is the intended behavior? Or am I missing something?

**Comment by kondziu** [comment]
Thanks. It's some kind of wild editing error. The correct text is even under the picture. I'm fixing it and updating the picture in the spec to comport to the implementation. Thanks, as usual, for paying attention.
